// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Persistence;

namespace Persistence.Migrations
{
    [DbContext(typeof(MainContext))]
    [Migration("20200427025805_AddDataDetailsTable")]
    partial class AddDataDetailsTable
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.14-servicing-32113")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Business.Entities.Debt", b =>
                {
                    b.Property<int>("IdDebt")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("DebtName");

                    b.Property<string>("DebtType");

                    b.Property<decimal>("DebtValue");

                    b.Property<string>("Debtor");

                    b.Property<int>("FeeQty");

                    b.Property<DateTime>("InitDate");

                    b.HasKey("IdDebt");

                    b.ToTable("Debts");
                });

            modelBuilder.Entity("Business.Entities.DebtDetail", b =>
                {
                    b.Property<int>("IdDebtDetail")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<decimal>("Capital");

                    b.Property<decimal>("Fee");

                    b.Property<int>("IdDebt");

                    b.Property<decimal>("Interest");

                    b.Property<decimal>("NumberFee");

                    b.HasKey("IdDebtDetail");

                    b.ToTable("DebtDetails");
                });
#pragma warning restore 612, 618
        }
    }
}
